version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  apt_packages:
    - doxygen
    - graphviz
  jobs:
    post_build:
      - cd ObjCryst/doc && doxygen
      - mv ObjCryst/doc/build/html/* "$READTHEDOCS_OUTPUT/html/"
sphinx:
  configuration: ObjCryst/doc/sphinx-objcryst/conf.py
